name: publish-image

on:
  push:
    branches: [main]      # ogni push su main ricostruisce
    paths-ignore:
      - 'README.md'
      - '.github/workflows/publish.yml'
  workflow_dispatch:      # puoi lanciarlo a mano dal tab “Actions”

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read      # serve a checkout
      packages: write     # serve a push su GHCR
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3          # login automatico con GITHUB_TOKEN
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/andy-image:1.0
            ghcr.io/${{ github.repository_owner }}/andy-image:latest
          context: .          # Dockerfile nella root del repo
